[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
inventory_core = { path = "../core", package = "core" }
serde = { version = "1.0", features = ["derive"] }

# Update rust-embed to version 8
rust-embed = "8.7.2"
